### ISSUE TITLE
Create a page about namecoin scalability

### ISSUE THREAD

**Issue by khalahan** [namecoin/wiki#10]
On the wiki : http://wiki.namecoin.info

Some possible content :
- Full node
- Pruned node (last k blocks)
- SPV Clients
- SCIP

**Comment by indolering** [comment]
Start of this here: https://bitcoin.stackexchange.com/questions/18386/scalability-of-namecoin

**Comment by indolering** [comment]
One question I have is how hard it would be to abstract the validation of various namespaces, allowing a semi-full-node for a specific namespace.   I don't understand the data structures well enough, but I'm guessing that we can't get away from having a full copy of Namecoin transactions, however, couldn't we just store the hash on leaves of namespaces we don't care about?

**Comment by indolering** [comment]
Done https://wiki.namecoin.info/index.php?title=Scalability
