### ISSUE TITLE
No link to the API wiki page

### ISSUE THREAD

**Issue by crosser** [namecoin/wiki#11]
There is no link to the "Client API" page from the main page of the wiki. Consequently, finding the API page is non-trivial. Please include a link. (It would make sense to check if there are other "orphan" pages.)

**Comment by phelixbtc** [comment]
obsolete?

**Comment by crosser** [comment]
Well, wiki migrated since then, but the problem still stands, right?

**Comment by crosser** [comment]
Well, ok, it's under "more proposed specifications", I guess that is ok then..

**Comment by phelixbtc** [comment]
The thing is, this page will never be up to date. It is much better to query the client about API calls or look into the code.

**Comment by indolering** [comment]
We are trying to setup an auto generated API page.
