### ISSUE TITLE
Migrate Github -> Mediawiki

### ISSUE THREAD

**Issue by indolering** [namecoin/wiki#2]
- [ ] Pull current wiki from Github @Ademan
- [ ] Convert remaining text to Wikitext @Ademan ?
- [ ] Import @Ademan  || copy and paste @indolering

There are only a few dozen pages, so it might not be worth actually building a XML restore file.  But if there is some sort of Gollum -> MediaWiki script out there I would prefer to not have to manually update everything ... again :p

**Comment by khalahan** [comment]
Is it not possible to add markdown support to mediawiki ?

**Comment by indolering** [comment]
I'm sure it's possible but not having a homogenous backend markup on the Github wiki has been both confusing and frustrating as one cannot just copy and paste and features in one markup are not available in the other (like including pages/lists, etc).  I'm sure that the same situation would arise in a mixed environment on mediawiki as well.
