### ISSUE TITLE
Setup Anti-Spam Protections

### ISSUE THREAD

**Issue by indolering** [namecoin/wiki#3]
- [x] Enable [Recaptcha](https://www.mediawiki.org/wiki/Extension:ConfirmEdit#ReCaptcha) (I do not care about your misgivings with Google, they are the only ones putting research into this and it is by far the best Captcha).
- [x] Enable [ConfrimEdit](https://www.mediawiki.org/wiki/Extension:ConfirmEdit) for new user signups and logins.
- [x] Enable [Nuke](https://www.mediawiki.org/wiki/Nuke#Installation) to help cleanup spam that gets past our protections.
- [ ] Install [Bad-Behavior](https://www.mediawiki.org/wiki/Extension:Bad_Behavior) to block bot form submissions.

@Ademan Help?

**Comment by khalahan** [comment]
I have public/private keys for reCaptcha on the forum (I guess I created them with my own google account). Do you need them ?

I've upgraded your permissions.

**Comment by indolering** [comment]
Sure, although I can use my own as well.

**Comment by indolering** [comment]
@khalahan Looks like I will need shell or SFTP access to make most of these changes.

**Comment by khalahan** [comment]
shell access & reCaptcha keys sent on BM.
