### ISSUE TITLE
Restrict editing

### ISSUE THREAD

**Issue by indolering** [namecoin/wiki#9]
Could someone turn on editing restrictions to only those with push privileges?  

@phelixbtc @khalahan Sorry to bug you, but I think you are the only ones that can do it.  Do @JeremyRand and @domob1812 have account-ownership access?  If so, I'll start bugging them as well ツ

**Comment by phelixbtc** [comment]
"Restrict editing to Users in Teams with PUSH access only." is currently active (and has been from the start IIRC).

**Comment by indolering** [comment]
nm on this, I talked it out with Khal.
